export const CartActionTypes = {
  TOGGLE_DROPDOWN: 'TOGGLE_DROPDOWN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  EMPTY_CART: 'EMPTY_CART'
};